//! Machine-checked ABI layout assertions.
//!
//! Generated by `pina migrations create`. Do not edit.
//!
//! Run `pina migrations create` after changing a schema; `pina migrations
//! check` fails when this file no longer matches the manifest. A layout
//! change that forgets an offset fails `cargo test` in the same change.

// manifest-sha256: 30a269999e9afd824ed5a155102ce0edcb7c4c1ca50076367e6432232db23476
// program-id: CurveqeE6jzkyHQMcWaGENzd7jrd8m9R1u4dZ17GnSa9
// version_type: u8

#![allow(clippy::identity_op, clippy::eq_op)]
#![allow(clippy::unreadable_literal)]

/// Program id recorded in the manifest.
pub const PROGRAM_ID: &str = "CurveqeE6jzkyHQMcWaGENzd7jrd8m9R1u4dZ17GnSa9";

/// ABI layout for the `LaunchConfig` account.
pub mod account_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "LaunchConfig";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "0b2d505bc47b5637f7fa988d7f3e90c3cba6fd104f86945305036f5f8ad80557";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 740;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 740;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("authority", MIGRATION_HEADER_SIZE + 0, 32),
		("quote_mint", MIGRATION_HEADER_SIZE + 32, 32),
		("amm_config", MIGRATION_HEADER_SIZE + 64, 32),
		("sqrt_start_price", MIGRATION_HEADER_SIZE + 96, 16),
		("migration_sqrt_price", MIGRATION_HEADER_SIZE + 112, 16),
		("curve_sqrt_prices", MIGRATION_HEADER_SIZE + 128, 256),
		("curve_liquidities", MIGRATION_HEADER_SIZE + 384, 256),
		("total_supply", MIGRATION_HEADER_SIZE + 640, 8),
		("sale_supply", MIGRATION_HEADER_SIZE + 648, 8),
		("migration_supply", MIGRATION_HEADER_SIZE + 656, 8),
		("creator_allocation", MIGRATION_HEADER_SIZE + 664, 8),
		("migration_quote_threshold", MIGRATION_HEADER_SIZE + 672, 8),
		("creator_vesting_cliff", MIGRATION_HEADER_SIZE + 680, 8),
		("creator_vesting_duration", MIGRATION_HEADER_SIZE + 688, 8),
		("fee_decay_duration", MIGRATION_HEADER_SIZE + 696, 8),
		("index", MIGRATION_HEADER_SIZE + 704, 8),
		("start_fee_rate", MIGRATION_HEADER_SIZE + 712, 4),
		("end_fee_rate", MIGRATION_HEADER_SIZE + 716, 4),
		("creator_fee_share", MIGRATION_HEADER_SIZE + 720, 4),
		("migration_fee_rate", MIGRATION_HEADER_SIZE + 724, 4),
		("creator_lp_share", MIGRATION_HEADER_SIZE + 728, 4),
		("partner_lp_share", MIGRATION_HEADER_SIZE + 732, 4),
		("base_decimals", MIGRATION_HEADER_SIZE + 736, 1),
		("segment_count", MIGRATION_HEADER_SIZE + 737, 1),
		("pool_creator_mode", MIGRATION_HEADER_SIZE + 738, 1),
		("bump", MIGRATION_HEADER_SIZE + 739, 1),
	];
}

/// ABI layout for the `Launch` account.
pub mod account_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "account:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Launch";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "ba0cb4917a65041aaae1f2a4801014839fa4093171ad9250987fac791cd0cc70";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 282;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 282;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("config", MIGRATION_HEADER_SIZE + 0, 32),
		("creator", MIGRATION_HEADER_SIZE + 32, 32),
		("base_mint", MIGRATION_HEADER_SIZE + 64, 32),
		("quote_mint", MIGRATION_HEADER_SIZE + 96, 32),
		("base_vault", MIGRATION_HEADER_SIZE + 128, 32),
		("quote_vault", MIGRATION_HEADER_SIZE + 160, 32),
		("pool", MIGRATION_HEADER_SIZE + 192, 32),
		("sqrt_price", MIGRATION_HEADER_SIZE + 224, 16),
		("quote_reserve", MIGRATION_HEADER_SIZE + 240, 8),
		("partner_fees", MIGRATION_HEADER_SIZE + 248, 8),
		("creator_fees", MIGRATION_HEADER_SIZE + 256, 8),
		("creator_claimed", MIGRATION_HEADER_SIZE + 264, 8),
		("activation_time", MIGRATION_HEADER_SIZE + 272, 8),
		("status", MIGRATION_HEADER_SIZE + 280, 1),
		("bump", MIGRATION_HEADER_SIZE + 281, 1),
	];
}

/// ABI layout for the `ConfigCreated` event.
pub mod event_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ConfigCreated";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4ab0c654e90f2d06dd96f8d410825c1b317b9a9bb6030cf4392b3b9562c89d4b";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 160;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 160;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("config", MIGRATION_HEADER_SIZE + 0, 32),
		("authority", MIGRATION_HEADER_SIZE + 32, 32),
		("quote_mint", MIGRATION_HEADER_SIZE + 64, 32),
		("amm_config", MIGRATION_HEADER_SIZE + 96, 32),
		("migration_sqrt_price", MIGRATION_HEADER_SIZE + 128, 16),
		("sale_supply", MIGRATION_HEADER_SIZE + 144, 8),
		("migration_supply", MIGRATION_HEADER_SIZE + 152, 8),
	];
}

/// ABI layout for the `LaunchCreated` event.
pub mod event_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "LaunchCreated";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "c6c9e8f59d5ca739ed0ca4e080ebc0f5dc16abec45d746b9b44cf1f2123aa269";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 144;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 144;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("config", MIGRATION_HEADER_SIZE + 32, 32),
		("creator", MIGRATION_HEADER_SIZE + 64, 32),
		("base_mint", MIGRATION_HEADER_SIZE + 96, 32),
		("total_supply", MIGRATION_HEADER_SIZE + 128, 8),
		("activation_time", MIGRATION_HEADER_SIZE + 136, 8),
	];
}

/// ABI layout for the `Traded` event.
pub mod event_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Traded";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "7557bf6eb69932692849f391c2af0a1234970f503397288a084a16b41a87bbb6";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 121;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 121;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("trader", MIGRATION_HEADER_SIZE + 32, 32),
		("is_buy", MIGRATION_HEADER_SIZE + 64, 1),
		("base_amount", MIGRATION_HEADER_SIZE + 65, 8),
		("quote_amount", MIGRATION_HEADER_SIZE + 73, 8),
		("fee", MIGRATION_HEADER_SIZE + 81, 8),
		("creator_fee", MIGRATION_HEADER_SIZE + 89, 8),
		("sqrt_price", MIGRATION_HEADER_SIZE + 97, 16),
		("quote_reserve", MIGRATION_HEADER_SIZE + 113, 8),
	];
}

/// ABI layout for the `Completed` event.
pub mod event_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Completed";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4090e205fb1734c3cc6e011209399da1b49a133b7bcf4072d9d84d613712c555";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 40;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 40;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("quote_reserve", MIGRATION_HEADER_SIZE + 32, 8),
	];
}

/// ABI layout for the `Graduated` event.
pub mod event_1_05 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:05";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Graduated";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "2f8caea269a25444954c706a0de86e4a580b65dd06f45c7b89c3cba5c48af81d";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 120;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 120;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("pool", MIGRATION_HEADER_SIZE + 32, 32),
		("pool_base", MIGRATION_HEADER_SIZE + 64, 8),
		("pool_quote", MIGRATION_HEADER_SIZE + 72, 8),
		("migration_fee", MIGRATION_HEADER_SIZE + 80, 8),
		("burned_base", MIGRATION_HEADER_SIZE + 88, 8),
		("burned_lp", MIGRATION_HEADER_SIZE + 96, 8),
		("creator_lp", MIGRATION_HEADER_SIZE + 104, 8),
		("partner_lp", MIGRATION_HEADER_SIZE + 112, 8),
	];
}

/// ABI layout for the `Claimed` event.
pub mod event_1_06 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:06";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "Claimed";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "99d261afee0cac44917b4aa9c9e81332e771e1a9c0a01066d30ad40fcfa2aace";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 73;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 73;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("claimant", MIGRATION_HEADER_SIZE + 32, 32),
		("kind", MIGRATION_HEADER_SIZE + 64, 1),
		("amount", MIGRATION_HEADER_SIZE + 65, 8),
	];
}

/// ABI layout for the `LaunchCreatorChanged` event.
pub mod event_1_07 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:07";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "LaunchCreatorChanged";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "b827f16492a635e74f03043573edb42cbf2a6436db888dd31b64b7cca74236cb";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 96;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 96;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("previous_creator", MIGRATION_HEADER_SIZE + 32, 32),
		("new_creator", MIGRATION_HEADER_SIZE + 64, 32),
	];
}

/// ABI layout for the `DustSwept` event.
pub mod event_1_08 {
	/// Manifest contract key.
	pub const KEY: &str = "event:1:08";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "DustSwept";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "f31c62c5e663e30c56fb88e2748b77978dd7ed394e4e75bf94a631dd4257726c";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 1;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 2;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 56;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 56;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("launch", MIGRATION_HEADER_SIZE + 0, 32),
		("amount", MIGRATION_HEADER_SIZE + 32, 8),
		("creator_fee", MIGRATION_HEADER_SIZE + 40, 8),
		("partner_fee", MIGRATION_HEADER_SIZE + 48, 8),
	];
}

/// ABI layout for the `CreateConfigInstruction` instruction.
pub mod instruction_1_00 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:00";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CreateConfigInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "09fae3b29908af7692845db4d9da2e60e0e83835ab140b8efde468d0a4bcaa52";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 611;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 611;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("index", MIGRATION_HEADER_SIZE + 0, 8),
		("sqrt_start_price", MIGRATION_HEADER_SIZE + 8, 16),
		("curve_sqrt_prices", MIGRATION_HEADER_SIZE + 24, 256),
		("curve_liquidities", MIGRATION_HEADER_SIZE + 280, 256),
		("migration_quote_threshold", MIGRATION_HEADER_SIZE + 536, 8),
		("total_supply", MIGRATION_HEADER_SIZE + 544, 8),
		("creator_allocation", MIGRATION_HEADER_SIZE + 552, 8),
		("creator_vesting_cliff", MIGRATION_HEADER_SIZE + 560, 8),
		("creator_vesting_duration", MIGRATION_HEADER_SIZE + 568, 8),
		("fee_decay_duration", MIGRATION_HEADER_SIZE + 576, 8),
		("start_fee_rate", MIGRATION_HEADER_SIZE + 584, 4),
		("end_fee_rate", MIGRATION_HEADER_SIZE + 588, 4),
		("creator_fee_share", MIGRATION_HEADER_SIZE + 592, 4),
		("migration_fee_rate", MIGRATION_HEADER_SIZE + 596, 4),
		("creator_lp_share", MIGRATION_HEADER_SIZE + 600, 4),
		("partner_lp_share", MIGRATION_HEADER_SIZE + 604, 4),
		("segment_count", MIGRATION_HEADER_SIZE + 608, 1),
		("base_decimals", MIGRATION_HEADER_SIZE + 609, 1),
		("pool_creator_mode", MIGRATION_HEADER_SIZE + 610, 1),
	];
}

/// ABI layout for the `CreateLaunchInstruction` instruction.
pub mod instruction_1_01 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:01";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "CreateLaunchInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "99356d4efb0a31a976e27a6564ad7a68383f9998a77997673bcb3bcb9dfe36c7";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 8;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 8;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("activation_time", MIGRATION_HEADER_SIZE + 0, 8),
	];
}

/// ABI layout for the `BuyInstruction` instruction.
pub mod instruction_1_02 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:02";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "BuyInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "40c46cb20b9a9d1c78cb9f407e1686f81025444e8c3bf3ff4bed398254d4be2a";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 16;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 16;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("quote_amount_in", MIGRATION_HEADER_SIZE + 0, 8),
		("minimum_base_out", MIGRATION_HEADER_SIZE + 8, 8),
	];
}

/// ABI layout for the `SellInstruction` instruction.
pub mod instruction_1_03 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:03";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SellInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "7bbf248f5f558b443a13dad5427cbc3320ab2951f135d51c3bd533cab9702684";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 16;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 16;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("base_amount_in", MIGRATION_HEADER_SIZE + 0, 8),
		("minimum_quote_out", MIGRATION_HEADER_SIZE + 8, 8),
	];
}

/// ABI layout for the `GraduateInstruction` instruction.
pub mod instruction_1_04 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:04";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "GraduateInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `ClaimPartnerFeesInstruction` instruction.
pub mod instruction_1_05 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:05";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ClaimPartnerFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `ClaimCreatorFeesInstruction` instruction.
pub mod instruction_1_06 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:06";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ClaimCreatorFeesInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `ClaimCreatorAllocationInstruction` instruction.
pub mod instruction_1_07 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:07";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "ClaimCreatorAllocationInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

/// ABI layout for the `SetLaunchCreatorInstruction` instruction.
pub mod instruction_1_08 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:08";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SetLaunchCreatorInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "9b9c5ef5e5266080f0261fd34ef26aa5f6241805a705d856e6ac34aee990320f";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 32;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 32;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
		("new_creator", MIGRATION_HEADER_SIZE + 0, 32),
	];
}

/// ABI layout for the `SweepQuoteDustInstruction` instruction.
pub mod instruction_1_09 {
	/// Manifest contract key.
	pub const KEY: &str = "instruction:1:09";
	/// Rust type name as declared in the program.
	pub const RUST_NAME: &str = "SweepQuoteDustInstruction";
	/// Current schema version.
	pub const VERSION: u32 = 0;
	/// Schema hash recorded for this version.
	pub const SCHEMA_SHA256: &str = "4d30c5a987a69cde3f10c23b93498ead2a16de2576027c1cf287e3813769bdc3";
	/// Width of the discriminator in bytes.
	pub const DISCRIMINATOR_BYTES: usize = 1;
	/// Byte offset of the migration version field.
	pub const VERSION_OFFSET: usize = 1;
	/// Width of the migration version field in bytes; zero without an envelope.
	pub const VERSION_BYTES: usize = 0;
	/// Bytes occupied by the discriminator and version envelope together.
	pub const MIGRATION_HEADER_SIZE: usize = 1;
	/// Payload size in bytes, excluding the envelope header.
	pub const PAYLOAD_SIZE: usize = 0;
	/// Total encoded size in bytes, including the envelope header.
	pub const SIZE: usize = MIGRATION_HEADER_SIZE + PAYLOAD_SIZE;
	/// Manifest payload size; must agree with `PAYLOAD_SIZE`.
	pub const MANIFEST_PAYLOAD_SIZE: usize = 0;
	/// `(name, absolute_offset, size)` in encoded bytes.
	pub const FIELDS: &[(&str, usize, usize)] = &[
	];
}

